# NUMPY


In [ ]:
# Create a list of 1,000,000 salaries ranging from 50,000 to 150,000
import random

salary_list = [random.randint(50000, 150000) for _ in range(10_000_000)]

In [ ]:
import statistics as stats

In [ ]:
%%timeit
stats.mean(salary_list)

2.79 s ± 508 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
import numpy as np

In [ ]:
%%timeit
np.mean(salary_list)

621 ms ± 7.15 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
my_array = np.array([1, 2, 3, 4, 5])

In [ ]:
my_array.mean()

np.float64(3.0)

In [ ]:
import numpy as np

In [ ]:
# Job titles
job_titles = np.array(["Data Analyst", "Data Scientist", "Data Engineer", "Machine Learning Engineer", "AI Engineer"])

# Base Salaries
base_salaries = np.array([60000, 80000, 75000, 90000, np.nan])

# Bonus rates
bonus_rates = np.array([.05, .1, .08, .12, np.nan])

In [ ]:
total_salaries = base_salaries * (1 + bonus_rates)
total_salaries

array([ 63000.,  88000.,  81000., 100800.,     nan])

In [ ]:
np.nanmean(total_salaries)

np.float64(83200.0)

In [ ]:
import numpy as np

In [ ]:
years_of_experience = np.array([1, 2, 3, 4, 5])

In [ ]:
years_of_experience

array([1, 2, 3, 4, 5])

In [ ]:
experience = np.array(range(1, 6))
experience

array([1, 2, 3, 4, 5])

In [ ]:
experience_plus_one = experience + 1
experience_plus_one

array([2, 3, 4, 5, 6])

In [ ]:
experience_minus_one = experience - 1
experience_minus_one

array([0, 1, 2, 3, 4])

In [ ]:
experience_double = experience * 2
experience_double

array([ 2,  4,  6,  8, 10])

In [ ]:
experience_half = experience / 2
experience_half

array([0.5, 1. , 1.5, 2. , 2.5])

In [ ]:
# Slicing - Get a subset of an array.Get the second and third job postings
experience[1:3]

array([2, 3])

In [ ]:
# Boolean - Get only job postings with more than 2 years experience.
experience_more_than_two = experience[experience > 2]
experience_more_than_two

array([3, 4, 5])

### Math Operations

In [ ]:
# Aggregate functions:
# sum: sum
# prod: product
# cumsum: cumulative sum
# cumprod: cumulative product

# Mathematical operations (we won't be going into this during the course):
# sqrt
# exp
# log
# sin
# cos

In [ ]:
# First lets create a list with 10 yearly salaries for a Senior Data Analyst job.
# We're just using a combination of the random library to get random integers between 100000 and 150000.
# Then using a for loop to get 10 (random) values.

import random as rd

In [ ]:
salary = [rd.randint(100000, 150000) for num in range(10)]
salary

[146774,
 117335,
 127526,
 117562,
 147272,
 117376,
 113111,
 145710,
 130431,
 140283]

In [ ]:
# Convert the list to a numpy array
salary_array = np.array(salary)
salary_array

array([146774, 117335, 127526, 117562, 147272, 117376, 113111, 145710,
       130431, 140283])

In [ ]:
# Calculate the total sum of salaries
total_sum_salaries = np.sum(salary_array)
total_sum_salaries

np.int64(1303380)

In [ ]:
# Calculate the product of the elements in the array salary_array
prod_salaries = np.prod(salary_array)
prod_salaries

np.int64(-2901908652556107776)

In [ ]:
# Calculate the cumulative sum of salary_array
cumulative_sum = np.cumsum(salary_array)
cumulative_sum

array([ 146774,  264109,  391635,  509197,  656469,  773845,  886956,
       1032666, 1163097, 1303380])

In [ ]:
# Calculate the cumulative product of salary_sarry
cumulative_prod = np.cumprod(salary_array)
cumulative_prod

array([              146774,          17221727290,     2196217994384540,
         -62637176098431144, -1330161513375631168,  4204045899560902656,
        3667013148438765568, -7902980058341195776, -7979894684471508992,
       -2901908652556107776])

### Statistics Operators

In [ ]:
# Calculate the mean of salary_array
average_salary = np.mean(salary_array)
average_salary

np.float64(130338.0)

In [ ]:
# Calculate the median
median_salary = np.median(salary_array)
median_salary

np.float64(128978.5)

In [ ]:
# Calculate the variance
salary_variance = np.var(salary_array, ddof=1)
salary_variance

np.float64(188567445.7777778)

In [ ]:
# Calculate the standard deviation
np.std(salary_array, ddof=1)

np.float64(13731.986228429512)

In [ ]:
# Calculate the minimum element in salary_array
min_salary = np.min(salary_array)
min_salary

np.int64(113111)

In [ ]:
# Calculate the maximum element in salary_array
max_salary = np.max(salary_array)
max_salary

np.int64(147272)

### NAN

In [ ]:
# Inserting Missing Values
salary_with_nan = np.array([12345, np.nan, 23553, 84467, 973783, np.nan], dtype=float )
salary_with_nan

array([ 12345.,     nan,  23553.,  84467., 973783.,     nan])

In [ ]:
# Replace Values with NaN
salary_with_nan[salary_with_nan < 20000] = np.nan
salary_with_nan

array([    nan,     nan,  23553.,  84467., 973783.,     nan])

### Where

In [ ]:
# np.where(condition)
salary_array = np.where(salary_array < 120_000, 120_000, salary_array)
salary_array

array([146774, 120000, 127526, 120000, 147272, 120000, 120000, 145710,
       130431, 140283])

### Random Sampling

In [ ]:
# np.random.normal
# Syntax: np.random.normal(loc=0.0, scale=1.0, size=None)

# A few other random sampling functions:
# np.random.rand
# np.random.randn
# np.random.randint
# np.random.random
# np.random.uniform
# np.random.binomial
# np.random.poisson

# Example
# Let's add some random noise to the salary_array to simulate salary variations.
# We can generate random values from a normal distribution with a mean of 0 and a
# standard deviation of 5000, then add these values to the salaries.

noise = np.random.normal(0, 5000, salary_array.size)
salary_array_with_noise = salary_array + noise
salary_array_with_noise

array([151357.91336081, 113102.75612899, 119464.29454807, 119035.73019006,
       150175.50849798, 120344.80493319, 120158.54878008, 144921.66028229,
       131680.12932315, 139734.82264176])